added support for parsing esp packets
PcapDotNet/Pcap.Net pull request #114
Opened 2019-05-29 19:12 UTC by danwgun

2019-06-21 07:00 UTC, bricknerb requested changes
1. Could you add tests? See GreTests and WiresharkCompareTests.
2. Could you add EspLayer?

I have different nits to make the style conform better with the rest of the code, let me know if you'd like me to add comments or I can just fix it after this is merged.

2019-06-21 07:00 UTC, bricknerb commented on PcapDotNet/src/PcapDotNet.Packets/Esp/EspDatagram.cs
> +            get { return new Datagram(Buffer, StartOffset + HeaderLength, Length - HeaderLength); }
Wouldn't that include the pading, pad length, next header and ICV?

2019-07-09 22:04 UTC, danwgun commented on PcapDotNet/src/PcapDotNet.Packets/Esp/EspDatagram.cs
> +            get { return new Datagram(Buffer, StartOffset + HeaderLength, Length - HeaderLength); }
> 1. Could you add tests? See GreTests and WiresharkCompareTests.
> 2. Could you add EspLayer?
> 
> I have different nits to make the style conform better with the rest of the code, let me know if you'd like me to add comments or I can just fix it after this is merged.

Thanks for checking out my PR. I'll continue working on this.

2019-07-09 22:06 UTC, danwgun commented on PcapDotNet/src/PcapDotNet.Packets/Esp/EspDatagram.cs
> +            get { return new Datagram(Buffer, StartOffset + HeaderLength, Length - HeaderLength); }
> Wouldn't that include the pading, pad length, next header and ICV?

I tried to replicate the way Wireshark parses these packets. It includes all of this data in the payload.

2019-07-20 06:48 UTC, bricknerb commented on PcapDotNet/src/PcapDotNet.Packets/Esp/EspDatagram.cs
> +            get { return new Datagram(Buffer, StartOffset + HeaderLength, Length - HeaderLength); }
Great, let me know when you want me to take another look.

2022-03-26 06:07 UTC, closed without merging